<script type="text/javascript">
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
],
function($, confirmation) {
    $('#product-addtocart-button').on('click', function (e){
        e.preventDefault();
		var btn = $(this);
        confirmation({
            title: 'Are you sure?',
            content: 'Do you want add this product to cart?',
            actions: {
                confirm: function () {},
                cancel: function () {}
            },
            buttons: [{
	            text: $.mage.__('NÃO'),
	            class: 'action-secondary action-dismiss',
	            click: function (event) {
	                this.closeModal(event);
	            }
	        }, {
	            text: $.mage.__('SIM'),
	            class: 'action-primary action-accept',
	            click: function (event) {
	             	product_addtocart_form.submit()
	            }
	        }]
        });
    });
});
</script>